"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { CreditCard, ExternalLink, Loader2 } from "lucide-react"

export default function SettingsPage() {
  const [data, setData] = useState<{
    email: string
    plan: string
    messageCount: number
    messageLimit: number
  } | null>(null)
  
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetch("/api/settings")
      .then((res) => res.json())
      .then((json) => {
        if (!json.error) setData(json)
        setLoading(false)
      })
      .catch(() => setLoading(false))
  }, [])

  const handleManageBilling = async () => {
    alert("Redirecting to billing portal...")
    // In production, fetch the Stripe portal link from an API and redirect
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <Loader2 className="h-8 w-8 animate-spin text-blue-600" />
      </div>
    )
  }

  if (!data) {
    return <p className="text-gray-500">Failed to load settings.</p>
  }

  const usagePercent = Math.min((data.messageCount / data.messageLimit) * 100, 100)

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Settings</h1>
        <p className="text-gray-600">Manage your account and subscription</p>
      </div>

      {/* Current Plan */}
      <Card>
        <CardHeader>
          <CardTitle>Subscription</CardTitle>
          <CardDescription>Manage your plan and billing</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="font-medium">Current Plan</p>
              <div className="flex items-center gap-2 mt-1">
                <Badge variant={data.plan === "PRO" || data.plan === "ENTERPRISE" ? "default" : "secondary"}>
                  {data.plan}
                </Badge>
                <span className="text-sm text-gray-600">
                  {data.plan === "BASIC" ? "Free" : data.plan === "PRO" ? "$99/month" : "Custom"}
                </span>
              </div>
            </div>
            <Button onClick={handleManageBilling}>
              <CreditCard className="h-4 w-4 mr-2" />
              Manage Billing
            </Button>
          </div>

          {/* Usage */}
          <div className="space-y-4 pt-4 border-t">
            <h4 className="font-medium">AI Usage This Month</h4>
            
            <div className="space-y-2">
              <div className="flex justify-between text-sm">
                <span>AI Messages</span>
                <span className={usagePercent >= 100 ? "text-red-600 font-bold" : ""}>
                  {data.messageCount.toLocaleString()} / {data.messageLimit.toLocaleString()}
                </span>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-2">
                <div 
                  className={`h-2 rounded-full ${usagePercent >= 100 ? "bg-red-600" : usagePercent > 80 ? "bg-yellow-500" : "bg-blue-600"}`}
                  style={{ width: `${usagePercent}%` }}
                />
              </div>
              <p className="text-xs text-gray-500">
                Number of AI responses generated by your agent across all conversations.
              </p>
            </div>
          </div>

          {data.plan === "BASIC" && (
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <p className="text-sm text-blue-800">
                <strong>Upgrade to Pro</strong> for 2,000 AI messages per month, custom domains, and advanced features.
              </p>
              <Button size="sm" className="mt-2" onClick={handleManageBilling}>
                Upgrade Now
                <ExternalLink className="h-3 w-3 ml-2" />
              </Button>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Account Info */}
      <Card>
        <CardHeader>
          <CardTitle>Account</CardTitle>
          <CardDescription>Your account information</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <p className="text-sm text-gray-600">Email</p>
            <p className="font-medium">{data.email}</p>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
